# Generated by Django 5.1.6 on 2025-02-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('site_admin', 'Site Admin'), ('plant_owner', 'Plant Owner'), ('data_analyst', 'Data Analyst'), ('drone_controller', 'Drone Controller')], default='plant_owner', max_length=20),
        ),
    ]
