# Generated by Django 5.1.3 on 2025-05-23 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='แถวที่')),
            ],
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_number', models.PositiveIntegerField(verbose_name='คอลัมน์ที่')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='plant.panelrow')),
            ],
        ),
        migrations.CreateModel(
            name='SolarPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อโรงไฟฟ้า')),
                ('location', models.CharField(max_length=255, verbose_name='ที่ตั้ง')),
                ('installed_capacity_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='กำลังการผลิต (kW)')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของโรง')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ชื่อโซน')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='plant.solarplant')),
            ],
        ),
        migrations.AddField(
            model_name='panelrow',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='plant.zone'),
        ),
    ]
