# Generated by Django 5.1.3 on 2025-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarplant',
            name='panels_per_row',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนแผงต่อแถว'),
        ),
        migrations.AddField(
            model_name='solarplant',
            name='rows_per_zone',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนแถวต่อโซน'),
        ),
        migrations.AddField(
            model_name='solarplant',
            name='zone_count',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนโซน'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('plant', 'name')},
        ),
    ]
