# Generated by Django 5.1.3 on 2025-05-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_solarplant_panels_per_row_solarplant_rows_per_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarplant',
            name='panels_per_row',
        ),
        migrations.RemoveField(
            model_name='solarplant',
            name='rows_per_zone',
        ),
        migrations.RemoveField(
            model_name='solarplant',
            name='zone_count',
        ),
    ]
