# Generated by Django 5.1.3 on 2025-05-25 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_remove_solarplant_panels_per_row_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solarplant',
            name='data_analyst',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'data_analyst'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_analyst_plants', to=settings.AUTH_USER_MODEL, verbose_name='นักวิเคราะห์ข้อมูล'),
        ),
        migrations.AddField(
            model_name='solarplant',
            name='drone_controller',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'drone_controller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drone_plants', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ควบคุมโดรน'),
        ),
    ]
