# Generated by Django 5.1.6 on 2025-05-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_solarplant_data_analyst_solarplant_drone_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarplant',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='ละติจูด'),
        ),
        migrations.AddField(
            model_name='solarplant',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='ลองจิจูด'),
        ),
        migrations.AlterField(
            model_name='solarplant',
            name='location',
            field=models.CharField(max_length=255, verbose_name='ที่ตั้งโรงไฟฟ้า'),
        ),
    ]
