# Generated by Django 5.1.6 on 2025-05-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_solarplant_latitude_solarplant_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='วันที่รายงาน')),
                ('is_analyzed', models.BooleanField(default=False, verbose_name='วิเคราะห์แล้ว')),
                ('analysis_details', models.TextField(blank=True, verbose_name='รายละเอียดการวิเคราะห์')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='plant.solarplant')),
            ],
        ),
    ]
