# Generated by Django 5.1.6 on 2025-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_inspectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='greenzone',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='redzone',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='yellowzone',
            field=models.FloatField(default=0),
        ),
    ]
