# Generated by Django 5.1.6 on 2025-05-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_inspectionreport_greenzone_inspectionreport_redzone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarpanel',
            name='actual_output_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='กำลังผลิตจริง (kW)'),
        ),
    ]
