# Generated by Django 5.1.6 on 2025-05-31 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_solarpanel_actual_output_kw'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelOutputLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('output_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_logs', to='plant.solarpanel')),
            ],
        ),
    ]
