# Generated by Django 5.1.3 on 2025-05-23 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0003_remove_solarplant_panels_per_row_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspections/')),
                ('description', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'ยังไม่วิเคราะห์'), ('analyzed', 'วิเคราะห์แล้ว'), ('issue_found', 'พบปัญหา'), ('complete', 'แก้ไขแล้ว')], default='pending', max_length=20)),
                ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_inspections', to=settings.AUTH_USER_MODEL)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.solarplant')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.zone')),
            ],
        ),
    ]
