# Generated by Django 5.1.3 on 2025-05-25 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneinspection',
            name='captured_date',
            field=models.DateField(default=datetime.date(2025, 5, 25), verbose_name='Image Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='droneinspection',
            name='captured_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Image Time'),
            preserve_default=False,
        ),
    ]
