# Generated by Django 5.1.3 on 2025-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_droneinspection_captured_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droneinspection',
            name='captured_date',
            field=models.DateField(blank=True, null=True, verbose_name='Image Date'),
        ),
        migrations.AlterField(
            model_name='droneinspection',
            name='captured_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Image Time'),
        ),
    ]
